### ISSUE TITLE
CrashDebug doesn't give the backtrace pointing hard-fault location using gdb crashdump

### ISSUE THREAD

**Issue by bugobliterator** [adamgreen/CrashDebug#19]
I am getting proper backtrace pinpointing the location of crash when using CrashDump generated via CrashCatcher. But when using the crashdump generated using GDB the backtrace points to the Hardfault context only, not the location that generated the Hardfault. I have attached the generated crash dumps and elf file for your reference.

[crash.zip](https://github.com/adamgreen/CrashDebug/files/7387712/crash.zip)

**Comment by adamgreen** [comment]
Yeah, if you break into CrashCatcher while it is running you won't really be able to see the full stack with GDB because [CrashCatcher switches to use its own private stack](https://github.com/adamgreen/CrashCatcher/blob/master/Core/src/CrashCatcher_armv7m.S#L47) incase the crash was caused by a stack overflow or corruption. The assembly language code in CrashCatcher's HardFault_Handler would also confuse GDB's stack unwinder since it doesn't have a standard function prolog.

If you have a debugger attached before the crash happens, you could set a breakpoint on ```HardFault_Handler``` to stop things before CrashCatcher switches the stack pointer.

**Comment by bugobliterator** [comment]
Understood, thanks so much for your wonderful work! In case you are interested, we are working on using your project here https://github.com/ArduPilot/ardupilot/pull/19008 .

**Comment by adamgreen** [comment]
> In case you are interested, we are working on using your project here ArduPilot/ardupilot#19008

That's very cool.

What exactly is the scenario where you attach GDB to diagnose a crash when CrashCatcher is in use? There might be some workaround that might be made to work but really the issue is that CrashCatcher was built assuming that a hardware debugger isn't available but you still want to get information off of the device to help diagnose what happened.
